/* Mediterranean islands.
 * lon/lat are real geographic coordinates (used both to place the island on the
 * map and to zoom to it). size is a relative blob-size hint for drawing. */
window.ISLANDS = [
  { name: "Sicily",      lon: 14.15, lat: 37.60, size: 34, blurb: "The largest island in the Mediterranean, crowned by Mount Etna." },
  { name: "Sardinia",    lon:  9.05, lat: 40.10, size: 32, blurb: "Rugged coves and the turquoise Costa Smeralda." },
  { name: "Cyprus",      lon: 33.20, lat: 35.10, size: 30, blurb: "Legendary birthplace of Aphrodite, at the eastern edge of the sea." },
  { name: "Corsica",     lon:  9.10, lat: 42.15, size: 26, blurb: "Napoleon's mountainous French homeland." },
  { name: "Crete",       lon: 24.80, lat: 35.25, size: 30, blurb: "Home of the Minoans and the myth of the Minotaur." },
  { name: "Euboea",      lon: 23.60, lat: 38.55, size: 22, blurb: "A long slender island hugging the Greek mainland." },
  { name: "Mallorca",    lon:  3.00, lat: 39.60, size: 22, blurb: "The largest of the Balearic Islands." },
  { name: "Lesbos",      lon: 26.30, lat: 39.20, size: 20, blurb: "Aegean island of olive groves and the poet Sappho." },
  { name: "Rhodes",      lon: 28.00, lat: 36.20, size: 20, blurb: "Once site of the Colossus, one of the Seven Wonders." },
  { name: "Corfu",       lon: 19.90, lat: 39.62, size: 18, blurb: "Lush Ionian island off the coast of Greece." },
  { name: "Chios",       lon: 26.05, lat: 38.40, size: 17, blurb: "Famous for its mastic trees." },
  { name: "Kefalonia",   lon: 20.60, lat: 38.20, size: 17, blurb: "The largest of the Ionian Islands." },
  { name: "Menorca",     lon:  4.10, lat: 39.95, size: 16, blurb: "The quieter, greener Balearic sister of Mallorca." },
  { name: "Ibiza",       lon:  1.43, lat: 38.98, size: 15, blurb: "Balearic island of hidden coves and nightlife." },
  { name: "Djerba",      lon: 10.90, lat: 33.80, size: 16, blurb: "Sun-drenched island off the Tunisian coast." },
  { name: "Zakynthos",   lon: 20.75, lat: 37.79, size: 15, blurb: "Home to the famous Navagio shipwreck beach." },
  { name: "Naxos",       lon: 25.52, lat: 37.10, size: 15, blurb: "The largest of the Cyclades." },
  { name: "Malta",       lon: 14.42, lat: 35.92, size: 14, blurb: "A tiny nation-island of honey-coloured stone." },
  { name: "Elba",        lon: 10.30, lat: 42.78, size: 13, blurb: "Napoleon's first place of exile." },
  { name: "Kos",         lon: 27.20, lat: 36.85, size: 14, blurb: "Birthplace of Hippocrates, father of medicine." },
  { name: "Ischia",      lon: 13.90, lat: 40.73, size: 12, blurb: "A volcanic spa island in the Bay of Naples." },
  { name: "Pantelleria", lon: 11.99, lat: 36.80, size: 12, blurb: "A black volcanic island between Sicily and Tunisia." },
  { name: "Mykonos",     lon: 25.35, lat: 37.45, size: 12, blurb: "Cycladic island of whitewashed windmills." },
  { name: "Santorini",   lon: 25.42, lat: 36.40, size: 12, blurb: "A dramatic caldera born of a volcanic eruption." },
  { name: "Formentera",  lon:  1.43, lat: 38.70, size: 10, blurb: "The smallest and quietest inhabited Balearic island." },
  { name: "Capri",       lon: 14.24, lat: 40.55, size: 10, blurb: "A glamorous rock and its famous Blue Grotto." },
  { name: "Procida",     lon: 14.02, lat: 40.76, size:  9, blurb: "A pastel-coloured fishing island near Naples." },
  { name: "Ponza",       lon: 12.96, lat: 40.90, size:  9, blurb: "The largest of the Pontine Islands." },
  { name: "Lipari",      lon: 14.95, lat: 38.47, size: 10, blurb: "The main island of the volcanic Aeolian archipelago." },
  { name: "Stromboli",   lon: 15.21, lat: 38.79, size:  9, blurb: "An ever-active volcano rising straight from the sea." },
  { name: "Favignana",   lon: 12.33, lat: 37.93, size:  9, blurb: "Butterfly-shaped chief of the Aegadian Islands." },
  { name: "Lampedusa",   lon: 12.60, lat: 35.51, size: 10, blurb: "Italy's southernmost point, closer to Africa than Sicily." },
  { name: "Gozo",        lon: 14.24, lat: 36.04, size: 10, blurb: "Malta's greener, more rural sister island." },
  { name: "Krk",         lon: 14.60, lat: 45.05, size: 11, blurb: "One of the largest Croatian Adriatic islands." },
  { name: "Brač",        lon: 16.65, lat: 43.32, size: 11, blurb: "Croatian island famed for Zlatni Rat beach and white stone." },
  { name: "Hvar",        lon: 16.65, lat: 43.15, size: 11, blurb: "Lavender fields and one of Croatia's sunniest isles." },
  { name: "Korčula",     lon: 17.13, lat: 42.95, size: 10, blurb: "Reputedly the birthplace of Marco Polo." },
  { name: "Vis",         lon: 16.18, lat: 43.05, size:  9, blurb: "The most remote inhabited Croatian island." },
  { name: "Lefkada",     lon: 20.71, lat: 38.72, size: 11, blurb: "An Ionian island joined to the mainland by a causeway." },
  { name: "Ithaca",      lon: 20.70, lat: 38.40, size:  9, blurb: "The legendary home of Homer's Odysseus." },
  { name: "Aegina",      lon: 23.50, lat: 37.74, size: 10, blurb: "A Saronic island known for its pistachios." },
  { name: "Hydra",       lon: 23.47, lat: 37.34, size:  9, blurb: "A car-free island of stone mansions and donkeys." },
  { name: "Paros",       lon: 25.15, lat: 37.08, size: 11, blurb: "A Cycladic island prized in antiquity for its marble." },
  { name: "Milos",       lon: 24.44, lat: 36.72, size: 11, blurb: "Volcanic island where the Venus de Milo was found." },
  { name: "Skiathos",    lon: 23.49, lat: 39.16, size:  9, blurb: "The cosmopolitan gem of the Sporades." },
  { name: "Samos",       lon: 26.80, lat: 37.75, size: 12, blurb: "Birthplace of the mathematician Pythagoras." },
  { name: "Karpathos",   lon: 27.15, lat: 35.55, size: 11, blurb: "A wind-swept island between Crete and Rhodes." },
  { name: "Patmos",      lon: 26.55, lat: 37.31, size:  9, blurb: "Where the Book of Revelation is said to have been written." }
];
